name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install valgrind
        run: sudo apt-get -y install valgrind
      - name: valgrind version
        run: valgrind --version
      - name: build
        run: make
      - name: test
        run: valgrind ./${{secrets.BINARY_NAME}}