name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build (Debug)
        run: make
        env:
          EXTRA_CFLAGS: "-g"

      - uses: Ximaz/valgrind-action@v1.2.0
        with:
          valgrind_flags: "--leak-check=full --error-exitcode=1 --log-file=valgrind.log"
          binary_path: "target/ft_tester"
          binary_args: ""
      
      - name: Test (std)
        run: make test